name: Update Homebrew Formula

# This workflow requires a HOMEBREW_TAP_TOKEN secret to be set in the repository
# The token needs write access to the homebrew-mac-power-tools repository
# Create a Personal Access Token at https://github.com/settings/tokens with repo scope

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.1)'
        required: true
        type: string

jobs:
  update-homebrew:
    runs-on: macos-latest
    
    steps:
    - name: Checkout mac-power-tools
      uses: actions/checkout@v4
      with:
        repository: mikejennings/mac-power-tools
        ref: ${{ github.event.inputs.version || github.event.release.tag_name }}
    
    - name: Get release info
      id: release
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION="${{ github.event.release.tag_name }}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Download tarball and calculate SHA256
        curl -sL "https://github.com/mikejennings/mac-power-tools/archive/refs/tags/${VERSION}.tar.gz" -o release.tar.gz
        SHA256=$(shasum -a 256 release.tar.gz | awk '{print $1}')
        echo "sha256=$SHA256" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        echo "SHA256: $SHA256"
    
    - name: Checkout homebrew-mac-power-tools
      uses: actions/checkout@v4
      with:
        repository: mikejennings/homebrew-mac-power-tools
        token: ${{ secrets.HOMEBREW_TAP_TOKEN || secrets.GITHUB_TOKEN }}
        path: homebrew-tap
    
    - name: Update Formula
      run: |
        VERSION="${{ steps.release.outputs.version }}"
        SHA256="${{ steps.release.outputs.sha256 }}"
        VERSION_NUM="${VERSION#v}"
        
        cd homebrew-tap
        
        # Update the formula (use sed -i.bak for compatibility, then remove backup)
        sed -i.bak "s|url \".*\"|url \"https://github.com/mikejennings/mac-power-tools/archive/refs/tags/${VERSION}.tar.gz\"|" Formula/mac-power-tools.rb
        sed -i.bak "s|sha256 \".*\"|sha256 \"${SHA256}\"|" Formula/mac-power-tools.rb  
        sed -i.bak "s|version \".*\"|version \"${VERSION_NUM}\"|" Formula/mac-power-tools.rb
        rm -f Formula/mac-power-tools.rb.bak
        
        # Show changes
        git diff
    
    - name: Commit and Push
      run: |
        cd homebrew-tap
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        VERSION="${{ steps.release.outputs.version }}"
        git add Formula/mac-power-tools.rb
        git commit -m "Update Mac Power Tools to ${VERSION}" || echo "No changes to commit"
        git push || echo "No changes to push"
    
    - name: Test Formula
      run: |
        echo "Formula updated successfully!"
        echo "Users can now update via:"
        echo "  brew update"
        echo "  brew upgrade mac-power-tools"