name: Test Mac Power Tools

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        echo "Setting up test environment"
        chmod +x mac
        chmod +x scripts/*.sh
    
    - name: Test version command
      run: |
        ./mac version
    
    - name: Test help command
      run: |
        ./mac help
    
    - name: Test info command (dry run)
      run: |
        ./mac info system
    
    - name: Check script syntax
      run: |
        for script in scripts/*.sh; do
          echo "Checking $script"
          bash -n "$script"
        done
    
    - name: Test main script syntax
      run: |
        bash -n mac
    
    - name: Verify file structure
      run: |
        test -f mac
        test -d scripts
        test -f scripts/mac-update.sh
        test -f scripts/mac-info.sh
        test -f scripts/mac-maintenance.sh
        test -f README.md
        test -f LICENSE
    
    - name: Test update dry run
      run: |
        echo "Testing update command structure"
        ./mac update --help 2>/dev/null || true
    
    - name: Summary
      run: |
        echo "✅ All tests passed!"
        echo "Mac Power Tools is ready for use"